import { FormEvent, useMemo, useState } from 'react';
import { apiDelete, apiGet, apiPostJson } from '../api';
import { formatDate, useApiData } from '../hooks';
import { Monitor, MonitorHit } from '../types';
import { EmptyState, ErrorState, LoadingSkeleton, MetricStrip, StatusBadge } from '../components/primitives';

type Kind = 'keyword' | 'material' | 'journal' | 'author';
type MonitorResponse = { items: Monitor[]; count: number; total_hits: number; today_new_hits: number };
const kindLabels: Record<Kind, string> = { keyword: '关键词', material: '材料', journal: '期刊', author: '作者' };

export default function Monitors({ onSelectPaper }: { onSelectPaper: (id: string) => void }) {
  const { data, error, loading, refresh } = useApiData<MonitorResponse>((signal) => apiGet('/api/library/monitors', { signal, cacheMs: 8_000 }), []);
  const hits = useApiData<{ items: MonitorHit[]; count: number }>((signal) => apiGet('/api/library/monitors/hits?limit=100', { signal, cacheMs: 8_000 }), []);
  const [open, setOpen] = useState(false); const [name, setName] = useState(''); const [query, setQuery] = useState(''); const [kind, setKind] = useState<Kind>('keyword'); const [autoDownload, setAutoDownload] = useState(false); const [message, setMessage] = useState(''); const [busy, setBusy] = useState('');
  const parsed = useMemo(() => (data?.items ?? []).map((item) => { try { return { item, filters: JSON.parse(item.filters_json || '{}') as Record<string, unknown> }; } catch { return { item, filters: {} as Record<string, unknown> }; } }), [data]);
  const create = async (event: FormEvent) => { event.preventDefault(); try { await apiPostJson('/api/library/monitors', { name: name || `${kindLabels[kind]}监控`, query_text: query, filters: { monitor_type: kind, [kind]: query }, auto_download_oa: autoDownload, enabled: true }); setMessage('监控已写入统一数据库；下次自动扫描或“立即执行”会记录具体命中。'); setName(''); setQuery(''); setOpen(false); refresh(); hits.refresh(); } catch (reason) { setMessage(reason instanceof Error ? reason.message : '监控创建失败。'); } };
  const action = async (id: string, key: string, work: () => Promise<void>) => { setBusy(`${key}:${id}`); try { await work(); refresh(); hits.refresh(); } catch (reason) { setMessage(reason instanceof Error ? reason.message : '监控操作失败。'); } finally { setBusy(''); } };
  const remove = (item: Monitor) => {
    if (!window.confirm(`删除监控“${item.name}”及其 ${item.total_hits ?? 0} 条命中历史？已创建的下载任务不会被删除。`)) return;
    void action(item.id, 'delete', async () => {
      const result = await apiDelete<{ deleted_hits: number }>(`/api/library/monitors/${encodeURIComponent(item.id)}`);
      setMessage(`已删除监控“${item.name}”及 ${result.deleted_hits} 条命中历史。`);
    });
  };  const enabled = data?.items.filter((item) => Boolean(item.enabled)).length ?? 0; const auto = data?.items.filter((item) => Boolean(item.auto_download_oa)).length ?? 0;
  return <div className="page-stack monitors-page">
    <section className="command-strip monitor-command"><div><StatusBadge tone="success">LOCAL RULES</StatusBadge><span>实时扫描后的命中会保存到本机数据库</span></div><button className="button primary" type="button" onClick={() => setOpen(true)}>＋ 创建监控</button></section>
    <MetricStrip items={[{ label: '监控总数', value: data?.count, tone: 'accent' }, { label: '已启用', value: enabled, tone: 'success' }, { label: '自动下载 OA', value: auto, tone: 'preprint' }, { label: '累计命中', value: data?.total_hits, tone: 'publication' }, { label: '今日新增命中', value: data?.today_new_hits, tone: 'warning' }]} />
    {message && <p className="inline-message" role="status">{message}</p>}
    <section className="section-block monitor-list-block"><header className="section-header"><div><span className="section-kicker">SAVED QUERIES</span><h2>监控规则</h2></div><span className="muted">规则、检查时间和命中数均来自本机数据库</span></header>
      {loading && <LoadingSkeleton rows={8} />}{error && <ErrorState message={error.message} offline={error.code === 'offline'} onRetry={refresh} />}{!loading && !error && !parsed.length && <EmptyState title="尚未创建监控" message="创建关键词、材料、期刊或作者监控。" action={<button className="button primary" type="button" onClick={() => setOpen(true)}>创建第一个监控</button>} />}
      <div className="monitor-list">{parsed.map(({ item, filters }) => { const monitorKind = String(filters.monitor_type || Object.keys(kindLabels).find((key) => filters[key] != null) || 'keyword') as Kind; const active = Boolean(item.enabled); return <article className="monitor-row" key={item.id}><div className={`monitor-kind ${monitorKind}`}><span>{monitorKind === 'keyword' ? '#' : monitorKind === 'material' ? '◇' : monitorKind === 'journal' ? '▤' : '○'}</span><small>{kindLabels[monitorKind] || '关键词'}</small></div><div className="monitor-copy"><div><h3>{item.name}</h3><StatusBadge tone={active ? 'success' : 'neutral'}>{active ? '启用' : '禁用'}</StatusBadge>{item.auto_download_oa ? <StatusBadge tone="preprint">自动下载 OA</StatusBadge> : null}</div><code>{item.query_text || '查询未提供'}</code><p>累计命中 {item.total_hits ?? 0} · 今日新增 {item.today_new_hits ?? 0} · 上次检查 {formatDate(item.last_checked_at, true)} · 上次命中 {formatDate(item.last_matched_at, true)}</p></div><div className="monitor-actions"><button className="mini-button" type="button" disabled={Boolean(busy)} onClick={() => action(item.id, 'auto', async () => { await apiPostJson(`/api/library/monitors/${encodeURIComponent(item.id)}/settings`, { auto_download_oa: !item.auto_download_oa }); setMessage(!item.auto_download_oa ? '已开启该规则的开放获取 PDF 自动下载。' : '已关闭该规则的自动下载。'); })}>OA {item.auto_download_oa ? '关闭' : '开启'}</button><button className="mini-button" type="button" disabled={Boolean(busy)} onClick={() => action(item.id, 'enabled', async () => { await apiPostJson(`/api/library/monitors/${encodeURIComponent(item.id)}/settings`, { enabled: !active }); setMessage(active ? '监控已暂停。' : '监控已启用。'); })}>{active ? '暂停' : '启用'}</button><button className="mini-button primary" type="button" disabled={!active || Boolean(busy)} onClick={() => action(item.id, 'run', async () => { const result = await apiPostJson<{ result: { matched: number; new_hits: number } }>(`/api/library/monitors/${encodeURIComponent(item.id)}/run`, {}); setMessage(`规则已执行：匹配 ${result.result.matched} 篇，新增命中 ${result.result.new_hits} 篇。`); })}>{busy === `run:${item.id}` ? '执行中…' : '立即执行'}</button><button className="mini-button danger" type="button" disabled={Boolean(busy)} onClick={() => remove(item)}>删除</button></div></article>; })}</div>
    </section>
    <section className="section-block"><header className="section-header"><div><span className="section-kicker">MONITOR HITS</span><h2>监控命中记录</h2></div><span className="muted">首次发现时间不会在重复扫描中丢失</span></header>{hits.loading && <LoadingSkeleton rows={4} />}{hits.error && <ErrorState message={hits.error.message} offline={hits.error.code === 'offline'} onRetry={hits.refresh} />}{!hits.loading && !hits.error && !hits.data?.items.length && <EmptyState title="尚未产生命中" message="启用规则后，等待下一次实时扫描，或点击“立即执行”。" />}{hits.data?.items.map((hit) => <button className="monitor-hit" type="button" key={hit.id} onClick={() => onSelectPaper(hit.canonical_paper_id)}><div><StatusBadge tone={hit.version_type === 'preprint' ? 'preprint' : 'publication'}>{hit.version_type === 'preprint' ? '预印本' : '论文'}</StatusBadge><strong>{hit.title || '论文标题未提供'}</strong><p>{hit.monitor_name} · 首次命中 {formatDate(hit.first_matched_at, true)} · 已复查 {hit.match_count} 次</p></div><small>{hit.source || '—'} · {formatDate(hit.publication_date)}</small></button>)}</section>
    {open && <div className="modal-layer" role="presentation" onMouseDown={(event) => { if (event.currentTarget === event.target) setOpen(false); }}><form className="monitor-form" role="dialog" aria-modal="true" aria-labelledby="monitor-form-title" onSubmit={create}><header><div><span className="section-kicker">NEW MONITOR</span><h2 id="monitor-form-title">创建监控</h2></div><button className="icon-button" type="button" aria-label="关闭创建监控" onClick={() => setOpen(false)}>×</button></header><label>监控类型<select value={kind} onChange={(event) => setKind(event.target.value as Kind)}><option value="keyword">关键词</option><option value="material">材料</option><option value="journal">期刊</option><option value="author">作者</option></select></label><label>名称<input autoFocus value={name} onChange={(event) => setName(event.target.value)} placeholder="例如：二维磁性材料" /></label><label>查询规则<input required value={query} onChange={(event) => setQuery(event.target.value)} placeholder={`输入${kindLabels[kind]}名称或查询词`} /></label><label className="check-control"><input type="checkbox" checked={autoDownload} onChange={(event) => setAutoDownload(event.target.checked)} />自动下载合法开放获取 PDF</label><p>规则在每次实时扫描后执行；所有命中都保留在本机数据库。</p><footer><button className="button ghost" type="button" onClick={() => setOpen(false)}>取消</button><button className="button primary" type="submit">保存监控</button></footer></form></div>}
  </div>;
}